fasta: /n/data1/hms/dbmi/park/SOFTWARE/REFERENCE/GRCh37d5/human_g1k_v37_decoy.fasta
# dbsnp: /n/data1/hms/dbmi/park/SOFTWARE/REFERENCE/GRCh37d5/dbSNP/GRCh37_latest_dbSNP_all.vcf.gz
# njobs: 60
# njobs: 500
njobs: 300
control_is_undiluted_nanoseq: Yes
restriction_enzyme_nanoseq:
noise_rens: ../test/from_abascal/NOISE_GRCh37.rens.bed.gz
snp_rens: ../test/from_abascal/SNP_GRCh37.rens.bed.gz
noise_wgns: ../test/from_abascal/NOISE_GRCh37.wgns.bed.gz
snp_wgns: ../test/from_abascal/SNP_GRCh37.wgns.bed.gz
dilute_ctrl_bam: